export const vehicleLocation = [
  "Ampara",
  "Anuradhapura",
  "Badulla",
  "Batticaloa",
  "Colombo",
  "Galle",
  "Gampaha",
  "Hambantota",
  "Jaffna",
  "Kalutara",
  "Kandy",
  "Kegalle",
  "Kilinochchi",
  "Kurunegala",
  "Mannar",
  "Matale",
  "Matara",
  "Moneragala",
  "Mullaitivu",
  "Nuwara Eliya",
  "Polonnaruwa",
  "Puttalam",
  "Ratnapura",
  "Trincomalee",
  "Vavuniya",
];
export const vehicleType = [
  "Luxury Car",
  "Premium Car",
  "General Car",
  "Bus",
  "Van",
  "Tuktuk/Three Wheelers",
];

export const colors = {
  green: "#9ef01a",
  darkGreen: "#70e000",
  darkerGreen: "#38b000",
};
